# Generated by Django 4.2 on 2024-09-08 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("albergue", "0002_usuario_alter_adopcion_adoptador_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="voluntario",
        ),
    ]
