# Generated by Django 4.2 on 2024-09-08 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("albergue", "0003_remove_animal_voluntario"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="voluntario",
            field=models.ForeignKey(
                limit_choices_to={"rol": "V"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
